# Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 



In [127]:
import numpy as np

a=[]
x=np.array([[1,2,3,4]])
for i in range(5):
    k=((x[0]**(4-i)))
    a.append(k)
    
np.array(np.transpose(a))

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]], dtype=int32)

### OR

In [128]:
import numpy as np
a = np.array ([1,2,3,4])
N=5
np.vander(a, N,increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

### OR

In [126]:
a = np.array ([1,2,3,4])
N=5
np.column_stack([a**(N-1-i) for i in range(N)])

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]], dtype=int32)

# Problem Statement 2: 
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 
The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 

i 1 2 3 4 5 6 7 8 9 10 

===== == == == == == == == == == == 

Input 10 20 30 40 50 60 70 80 90 100  

y1 25 = (10+20+30+40)/4 

y2 35 = (20+30+40+50)/4 

y3 45 = (30+40+50+60)/4 

y4 55 = (40+50+60+70)/4 

y5 65 = (50+60+70+80)/4 

y6 75 = (60+70+80+90)/4 

y7 85 = (70+80+90+100)/4 

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

#### Question:
Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [231]:
def moving_ave(x,y):
    a=[]

    print("moving average sequence has: {} values".format((len(x)-y+1)))
    print("**" * 50)
    for k in range(len(x)- y+1):
        m=round((sum(x[k:k+y])/y),2)     #round for decimal values upto 2 places
        a.append(m)
    
    return a
   

In [232]:
moving_ave([10, 20, 30, 40, 50, 60, 70, 80, 90, 100],4)

moving average sequence has: 7 values
****************************************************************************************************


[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]

In [233]:
moving_ave([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3)

moving average sequence has: 11 values
****************************************************************************************************


[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]