# build the random forest model after  normalizing the variable to house pricing from boston data set. 

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn import datasets

In [3]:
boston = datasets.load_boston() 

In [4]:
features = pd.DataFrame(boston.data,  columns=boston.feature_names) 
features

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [5]:
targets = boston.target 
targets

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [6]:
scaler=StandardScaler()
X= scaler.fit_transform(features)

In [8]:
X =  pd.DataFrame(X,columns=boston.feature_names)
X

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.419782  0.284830 -1.287909 -0.272599 -0.144217  0.413672 -0.120013   
1   -0.417339 -0.487722 -0.593381 -0.272599 -0.740262  0.194274  0.367166   
2   -0.417342 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812   
3   -0.416750 -0.487722 -1.306878 -0.272599 -0.835284  1.016303 -0.809889   
4   -0.412482 -0.487722 -1.306878 -0.272599 -0.835284  1.228577 -0.511180   
..        ...       ...       ...       ...       ...       ...       ...   
501 -0.413229 -0.487722  0.115738 -0.272599  0.158124  0.439316  0.018673   
502 -0.415249 -0.487722  0.115738 -0.272599  0.158124 -0.234548  0.288933   
503 -0.413447 -0.487722  0.115738 -0.272599  0.158124  0.984960  0.797449   
504 -0.407764 -0.487722  0.115738 -0.272599  0.158124  0.725672  0.736996   
505 -0.415000 -0.487722  0.115738 -0.272599  0.158124 -0.362767  0.434732   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
0    0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  
1    0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.492439  
2    0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  
3    1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.361517  
4    1.077737 -0.752922 -1.106115  0.113032  0.441052 -1.026501  
..        ...       ...       ...       ...       ...       ...  
501 -0.625796 -0.982843 -0.803212  1.176466  0.387217 -0.418147  
502 -0.716639 -0.982843 -0.803212  1.176466  0.441052 -0.500850  
503 -0.773684 -0.982843 -0.803212  1.176466  0.441052 -0.983048  
504 -0.668437 -0.982843 -0.803212  1.176466  0.403225 -0.865302  
505 -0.613246 -0.982843 -0.803212  1.176466  0.441052 -0.669058  

[506 rows x 13 columns]

In [21]:
# Maximum price
maximum_price= targets.max()*1000 
print("$" + str(maximum_price))

$50000.0


In [22]:
# Minimum price
minimum_price= targets.min()*1000 
print("$" + str(minimum_price))

$5000.0


In [23]:
# Mean price
mean_price=targets.mean()*1000 
print("$" + str(mean_price))

$22532.806324110676


In [25]:
y = targets

In [27]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.25, random_state= 355)

In [60]:
#let's first visualize the tree on the data without doing any pre processing
from sklearn import tree
from sklearn.tree import DecisionTreeRegressor
clf = DecisionTreeRegressor( min_samples_split= 2)

In [61]:
clf.fit(x_train,y_train)

DecisionTreeRegressor()

In [62]:
clf.score(x_test,y_test)

0.6800272882088918

In [63]:
# Now Random forest

In [64]:
from sklearn.ensemble import RandomForestRegressor

In [65]:
rand_clf = RandomForestRegressor(random_state=6)

In [66]:
rand_clf.fit(x_train,y_train)

RandomForestRegressor(random_state=6)

In [68]:
rand_clf.score(x_test,y_test)

0.8738599772550173

In [81]:
a=scaler.fit_transform([[0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33],
                        [0.07,0.1,2.15,0.0,0.6,7.6,55,6.1,2,222.0,18.7,396.90,5.8]])
a

array([[-1., -1.,  1.,  0., -1., -1., -1., -1.,  1.,  0.,  0.,  0., -1.],
       [ 1.,  1., -1.,  0.,  1.,  1.,  1.,  1., -1.,  0.,  0.,  0.,  1.]])

In [87]:
rand_clf.predict(a)

array([23.666, 19.121])

In [86]:
rand_clf.predict([[-0.402961,-0.487722,2.422565,-0.272599,0.469104,-1.183370,0.857902,-0.938447,-0.637962,1.798194,0.760340,0.421206,0.757911]])

array([13.106])